models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    content = db.Column(db.String(300), nullable=False)

    def __repr__(self):
        return f"<Note {self.id}: {self.title}"

app.py
# import os
# from flask_sqlalchemy import SQLAlchemy
from flask import Flask, request, jsonify, render_template, redirect, url_for
from config import Config
from models import Note, db
from notes.routes import notes_bp

app = Flask(__name__)
app.config.from_object(Config)
db.init_app(app)
app.register_blueprint(notes_bp)


# DB_FILE_PATH = os.path.join(os.path.dirname(__file__), "notes.sqlite")
#
# app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{DB_FILE_PATH}"
# app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

# db = SQLAlchemy(app)


# class Note(db.Model):
#    id = db.Column(db.Integer, primary_key=True)
#    title = db.Column(db.String(100), nullable=False)
#    content = db.Column(db.String(300), nullable=False)
#
#    def __repr__(self):
#        return f"<Note {self.id}: {self.title}"


# @app.route("/")
# def hello():
# return "Hello World from Flask!"
# role = "admin"
# notes = [{"title": "Titulo de prueba", "content": "Contenido de prueba"}]
#    notes = Note.query.all()
# return render_template("home.html", role=role, notes=notes)
#    return render_template("home.html", notes=notes)
# return "Hello World"


@app.route("/acerca-de")
def about():
    return "Esto es una app de notas"


@app.route("/contacto", methods=["GET", "POST"])
def contact():
    if request.method == "POST":
        return "Formulario enviado correctamente.", 201
    return "Página de contacto"


# @app.route("/api/info")
# def api_info():
#    data = {"nombre": "Notes App", "version": "1.1.1"}
#    return jsonify(data), 200
#    return jsonify(data)


@app.route("/confirmacion")
def confirmation():
    return "Recibido"


# @app.route("/crear-nota", methods=["GET", "POST"])
# def create_note():
#    if request.method == "POST":
# note = request.form.get("note", "No encontrada")
#        title = request.form.get("title", "")
#        content = request.form.get("content", "")

#        note_db = Note(title=title, content=content)

#        db.session.add(note_db)
#        db.session.commit()
# print(note)
# return redirect(url_for("confirmation", note=note))
#        return redirect(url_for("hello"))
#    return render_template("note_form.html")


# @app.route("/editar-nota/<int:id>", methods=["GET", "POST"])
# def edit_note(id):
#    note = Note.query.get_or_404(id)
#    if request.method == "POST":
#        title = request.form.get("title", "")
#        content = request.form.get("content", "")
#        note.title = title
#        note.content = content
#        db.session.commit()
#        return redirect(url_for("hello"))
#    return render_template("edit_note.html", note=note)


# @app.route("/eliminar-nota/<int:id>", methods=["POST"])
# def delete_note(id):
#    note = Note.query.get_or_404(id)
#    db.session.delete(note)
#    db.session.commit()
#    return redirect(url_for("hello"))


# if __name__ == "__main__":
#    app.run(debug=True)

notes/routes.py
from flask import request, jsonify, render_template, redirect, url_for, Blueprint, flash
from models import Note, db

notes_bp = Blueprint("notes", __name__)


@notes_bp.route("/")
def hello():
    # return "Hello World from Flask!"
    # role = "admin"
    # notes = [{"title": "Titulo de prueba", "content": "Contenido de prueba"}]
    notes = Note.query.all()
    # return render_template("home.html", role=role, notes=notes)
    return render_template("home.html", notes=notes)
    # return "Hello World"


@notes_bp.route("/crear-nota", methods=["GET", "POST"])
def create_note():
    if request.method == "POST":
        # note = request.form.get("note", "No encontrada")
        title = request.form.get("title", "")
        content = request.form.get("content", "")

        note_db = Note(title=title, content=content)

        db.session.add(note_db)
        db.session.commit()
        flash("Nota creada!!", "success")
        # print(note)
        # return redirect(url_for("confirmation", note=note))
        return redirect(url_for("notes.hello"))
    return render_template("note_form.html")


@notes_bp.route("/editar-nota/<int:id>", methods=["GET", "POST"])
def edit_note(id):
    note = Note.query.get_or_404(id)
    if request.method == "POST":
        title = request.form.get("title", "")
        content = request.form.get("content", "")
        note.title = title
        note.content = content
        db.session.commit()
        return redirect(url_for("notes.hello"))
    return render_template("edit_note.html", note=note)


@notes_bp.route("/eliminar-nota/<int:id>", methods=["POST"])
def delete_note(id):
    note = Note.query.get_or_404(id)
    db.session.delete(note)
    db.session.commit()
    return redirect(url_for("notes.hello"))

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {% block title %} App Notas {% endblock title %}</title>
    <link href="css/style.css" rel="stylesheet">
  </head>
  <body style="background-color: aqua;">

    {% with messages=get_flashed_messages(with_categories=True) %}
      {% if messages %}
      <ul>
        {% for category,message in messages %}
          <li class="{{ category }}"> {{message}}</li>
        {% endfor %}
      </ul>
      {% endif %}
    {% endwith %}

    {% block content %}
    {% endblock content %}
  </body>
</html>

templates/edit_note.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Crear una nueva nota</title>
    <link href="css/style.css" rel="stylesheet">
  </head>
  <body>
    <h1>Editar Nota</h1>
    <form method="POST">
      <label for="title">Título</label>
      <input type="text" name="title" id="title" value="{{ note.title }}">
      <br>
      <label for="content">Contenido</label>
      <input type="text" name="content" id="content" value="{{ note.content }}">

      <input type="submit" name="" value="Actualizar nota">
    </form>
  </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}


    <h1>Notas:</h1>
    <ul>
      {% for note in notes%}
      <li>{{ note.title }}
          <br>
          {{ note.content }}
          <br>
          <a href="{{ url_for('notes.edit_note', id=note.id) }}">Editar</a>
          <form action="{{ url_for("notes.delete_note", id=note.id) }}" method="post">
            <button type="submit">Eliminar</button>
          </form>
      </li>
      {% else %}
      Aun no se han creado notas!
      {% endfor %}
    </ul>

    <a href="{{ url_for('notes.create_note') }}">Agregar una nueva nota</a>

{% endblock content %}

templates/note_form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Crear una nueva nota</title>
    <link href="css/style.css" rel="stylesheet">
  </head>
  <body>
    <h1>Crear una nueva nota</h1>
    <form method="POST">
      <label for="nota">
        nota
      </label>
      <input type="text" name="note" id="note">
      <input type="submit" name="" value="crear nota">
    </form>
  </body>
</html>